Don't filter op2ext.o in test code
Now that the undefined reference to `_ReturnAddress` problem has been
solved, there is no longer a requirement to filter that object file.